config/routes.rb
Mcblooms::Application.routes.draw do
  resources :ingredients

  get "registration/new"
  mount Ckeditor::Engine => "/ckeditor"
  resources :categories do
    resources :products do
      resources :prices
    end
  end
  resources :pages

  resources :products do
    resources :prices
  end
  resource :cart, controller: :cart, path: 'your-basket', only: [:show, :destroy, :update] do
    resource :checkout, controller: :checkout, only: [:show, :create]
  end
  resources :my_orders, only: [:index, :show]

  post "my-basket/add/:product_id/:price_id", to: 'cart_items#update', as: :add_to_cart
  delete "my-basket/remove/:product_id/:price_id", to: 'cart_items#destroy', as: :remove_from_cart

  resource :my_profile, path: 'my-profile', controller: 'my_profile' do
    resources :addresses do
      member do
        post :mark_default
      end
    end
    resources :favorites, only: [:index, :update, :destroy]
  end

  get "register", to: 'registration#new', as: :registration
  post "register", to: 'registration#create'

  resources :menus
  resources :users

  get "signin", to: "sessions#new", as: :signin
  get "signout", to: "sessions#destroy", as: :signout
  resources :sessions, only: [:create]
  resources :password_reset, only: [:new, :create, :edit, :update], controller: :password_reset

  root 'home#index'
end

app/controllers/my_profile_controller.rb
class MyProfileController < ApplicationController
  respond_to :html, :json
  def show
    authorize! :show, user
    respond_with user
  end

  def edit
    authorize! :edit, user
    respond_with user
  end

  def update
    authorize! :update, user
    flash[:notice] = "#{user.name} was updated successfully" if user.update_attributes(profile_params)
    respond_with user, location: my_profile_url
  end

  #######
  private
  #######
  
  def user
    return nil unless current_user
    @user ||= current_user.decorate
    @user
  end

  def profile_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/views/my_profile/_form.html.slim
= simple_form_for(@user, url: my_profile_url(), method: "PUT") do |f|
  = f.error_notification

  .form-inputs
    = f.input :first_name
    = f.input :last_name
    = f.input :email

  fieldset
    legend Password
    - if @user.persisted?
      p.text-danger Leave blank if you don't want to change the current password
    = f.input :password
    = f.input :password_confirmation

  .form-actions
    = f.button :submit
    span.or  or  
    = link_to "Cancel", my_profile_url, class: "btn-cancel"

app/views/my_profile/edit.html.slim
- title "Editing #{@user.name}"

== render 'form'

app/views/my_profile/show.html.slim
- title "Profile for #{@user.name}"
dl.dl-horizontal
  dt First Name
  dd = @user.first_name
  dt Last Name
  dd = @user.last_name
  dt Email
  dd = mail_to @user.email
  

.btn-group.actions
  = link_to_btn "Edit Profile", edit_my_profile_path(), type: :primary, icon: :pencil if can? :edit, @user