config/routes.rb
Mcblooms::Application.routes.draw do
  resources :ingredients

  get "registration/new"
  mount Ckeditor::Engine => "/ckeditor"
  resources :categories do
    resources :products do
      resources :prices
    end
  end
  resources :pages

  resources :products do
    resources :prices
  end
  resource :cart, controller: :cart, path: 'your-basket', only: [:show, :destroy, :update] do
    resource :checkout, controller: :checkout, only: [:show, :create]
  end
  resources :my_orders, only: [:index, :show]

  post "my-basket/add/:product_id/:price_id", to: 'cart_items#update', as: :add_to_cart
  delete "my-basket/remove/:product_id/:price_id", to: 'cart_items#destroy', as: :remove_from_cart

  resource :my_profile, path: 'my-profile', controller: 'my_profile' do
    resources :addresses do
      member do
        post :mark_default
      end
    end
    resources :favorites, only: [:index, :update, :destroy]
  end

  get "register", to: 'registration#new', as: :registration
  post "register", to: 'registration#create'

  resources :menus
  resources :users

  get "signin", to: "sessions#new", as: :signin
  get "signout", to: "sessions#destroy", as: :signout
  resources :sessions, only: [:create]
  resources :password_reset, only: [:new, :create, :edit, :update], controller: :password_reset

  root 'home#index'
end

app/models/price.rb
class Price
  CONSUMER = 'consumer'
  DISTRIBUTOR = 'distributor'
  VALID_TARGETS = [CONSUMER, DISTRIBUTOR]

  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Alize
  field :amount, type: Money
  field :quantity, type: Integer, default: 1
  field :name, type: String
  field :brief, type: String
  field :target, type: String
  field :size_id, type: String

  embedded_in :product
  has_many :featured_products

  accepts_nested_attributes_for :featured_products, allow_destroy: true

  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :quantity, presence: true, numericality: { greater_than: 0 }
  validates :target, presence: true
  validates :size_id, presence: true

  validate :valid_target

  def self.target_collection
    VALID_TARGETS.map { |target| [target.to_s.humanize, target] }
  end

  def size
    return @size ||= product.sizes.find(size_id)
  rescue Mongoid::Errors::DocumentNotFound
    return nil
  end

  def dim_weight
    quantity * size.dim_weight
  end

  #######
  private
  #######


  def valid_target
    errors.add(:target, "#{target} is not a valid target") unless VALID_TARGETS.include?(target)
  end
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  respond_to :html, :json
  before_action :product
  before_action :price, only: [:show, :edit, :update, :destroy]
  helper_method :category, :product, :price

  def index
    @prices = product.prices.all.decorate
    respond_with @prices
  end

  def show
    respond_with @price
  end

  def new
    @price = product.prices.new
    respond_with @price
  end

  def edit
    respond_with @price
  end

  def create
    @price = product.prices.new(price_params)
    flash[:notice] = 'Price was successfully created.' if @price.save
    respond_with @price, location: [category, product]
  end

  def update
    flash[:notice] = 'Price was successfully updated.' if @price.update_attributes(price_params)
    respond_with @price, location: [category, product]
  end

  def destroy
    price.destroy
    respond_with @price, location: [product]
  end

  #######
  private
  #######


  # Use callbacks to share common setup or constraints between actions.
  def price
    return if params[:id].nil?
    @price = product.prices.find(params[:id])
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def price_params
    params.require(:price).permit(
      :size_id,
      :quantity,
      :amount,
      :name,
      :brief,
      :target,
      featured_products_attributes: [
        :id,
        :start_time,
        :end_time,
        :importance,
        :_destroy
      ]
    )
  end

  def product
    return if params[:product_id].nil?
    @product ||= Product.find(params[:product_id])
  end

  def category
    return if params[:category_id].nil?
    @category ||= Category.find(params[:category_id])
  end
end

app/views/prices/_featured_product_fields.html.slim
.item
  .actions = remove_nested_item(f, size: :xs)
  = f.input :id, as: :hidden if f.object.persisted?
  = f.input :start_time, as: :calendar
  = f.input :end_time, as: :calendar
  = f.input :importance, as: :number, input_html: {min: 1, max: 10}, hint: "1 being <strong>very important</strong>, 10 being not important at all".html_safe

app/views/prices/_form.html.slim
= simple_form_for([category, product, @price]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :size_id, collection: product.sizes.map{|s| [s, s.id]}, as: :radio_buttons, hint: "To add different size, please edit the product #{link_to "here", ["edit", category, product]}".html_safe
    = f.input :quantity, hint: "How many of the size above are included for this price? (e.g. case would include 12 bottles). For single units please enter 1"
    = f.input :amount, hint: "What is the cost for this?"
    = f.input :name, hint: "(e.g. Case of 6 oz bottles) - if blank it will be auto generated"
    = f.input :brief, hint: "Why is this price different from all the other prices for this product?"
    = f.input :target, collection: Price.target_collection, as: :radio_buttons, hint: "Select who can see these prices?"

  fieldset.featurable
    legend Homepage Feature
    = nested_objects(f, :featured_products)

  .form-actions
    = f.button :submit
    span.or  or
    = link_to "Cancel", [category, product, Price], class: "btn-cancel"

app/views/prices/_price.html.slim
- if can? :show, price
  = div_for(price, class: "") do
    .name = price.name
    .row
      .amount.col-sm-6
        = number_to_currency price.amount
      .add-to-cart.col-sm-6
        = link_to_btn "Add to cart", add_to_cart_path(price.product, price), method: :post, type: :primary, icon: 'shopping-cart', class: "pull-right"
    -if can? :manage, price
      .actions
        .btn-group.pull-right
          = link_to_btn "", ["edit", @category, @product, price], size: :xs, icon: "pencil"
          = link_to_btn "", [@category, @product, price], size: :xs, type: :danger, icon: "times", data: {confirm: "Remove this price?"}
        span.hint Visible to #{price.target.humanize}

app/views/prices/edit.html.slim
- title "Editing price"

== render 'form'

.btn-group
  = link_to_btn 'Back to product', [category, product], icon: 'arrow-left'

app/views/prices/index.html.slim
- title "Listing prices"

table.table
  thead
    tr
      th Size
      th Amount
      th Name
      th Target
      th
      th
  tbody
    - @prices.each do |price|
      tr
        td = price.size
        td = price.amount
        td = price.name
        td = price.target
        td = link_to_btn '', ["edit", category, product, price], icon: "pencil", type: :info, data: {toggle: "tooltip"}, title: "Edit", size: "sm"
        td = link_to_btn '', [category, product, price], :confirm => 'Are you sure?', :method => :delete, icon: "remove", type: :danger, data: {toggle: "tooltip"}, title: "Delete", size: "sm"

.btn-group
  = link_to_btn 'New Price', ["new", category, product, "price"], icon: "plus", type: :primary
  = link_to_btn "Back to #{product.name}", [category, product], icon: "arrow-left"

app/views/prices/new.html.slim
- title "New price"

== render 'form'

= link_to_btn 'Back to prices', [category, product, Price], icon: "arrow-left"

app/views/prices/show.html.slim
- title "price"
dl.dl-horizontal
  dt Size
  dd = @price.size
  dt Amount
  dd = @price.amount
  dt Name
  dd = @price.name
  dt Brief
  dd = @price.brief
  dt Target
  dd = @price.target

.btn-group
  = link_to_btn 'Edit', edit_price_path(@price), icon: 'pencil', type: :primary if can? :edit, @price
  = link_to_btn 'Back', prices_path, icon: "arrow-left"